// 扩展图标
$.LKExtendICON({
  'starter' : 'chevron-circle-down',
  'starter-closed' : 'chevron-circle-up',
  'starter-back' : 'chevron-circle-left',
  'menu-next' : 'caret-right',

  'UNKNOWN' : 'question',
  'SECRECY' : 'user-secret',
  'ALIEN' : 'bug',
  'FEMALE' : 'female',
  'MALE' : 'male',

  'sysMgmt' : 'cog',
  'roleMgmt' : 'user-secret',
  'userMgmt' : 'user',
  'dictMgmt' : 'book',
  'loginLog' : 'address-book',
  'operLog' : 'book-open',
  'errorLog' : 'times',
  'appMgmt' : 'mobile-alt',
  'appVersionMgmt' : 'code-branch',
  'appBannerMgmt' : 'film',
  'appNewsMgmt' : 'newspaper',
  'appFeedbackMgmt' : 'comment',
  'appScoreMgmt' : 'star',
  'websiteMgmt' : 'desktop',
  'websiteBannerMgmt' : 'film',
  'websiteNewsMgmt' : 'newspaper',
  'orgMgmt' : 'sitemap',
  'compMgmt' : 'building',
  'deptMgmt' : 'suitcase',
  'employeeMgmt' : 'user-friends',
  'workflowMgmt' : 'project-diagram',
  'dictTimeMgmt' : 'clock',
  'employeeAttendance' : 'calendar-check',
});
